name: Build-Curl
# tells github which repository events should trigger this workflow
on:
  workflow_dispatch
permissions: {}
# the code that will run in the cloud
jobs:
  build-and-curl:
    runs-on: ubuntu-latest
    steps:
    - name: get-code
      # uses tag runs a premade action from github marketplace
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: docker-build
      run: |
        docker build -t pipeline-test .
    - name: docker-run
      env:
        DJANGO_SECRET_KEY: ${{}}
      run: |
        docker run -p 8000:8000 -e DJANGO_SECRET_KEY="wahwah" -d pipeline-test
    - name: curl-ftw
      run: |
        sleep 10
        curl -f http://localhost:8000/
